### ISSUE TITLE
Cannot use Unicons with font hosted locally

### ISSUE THREAD

**Issue by Unknow-max** [Iconscout/unicons#102]
*Hi*,
 I want to use Unicons font locally on my machine, with the dedicated `line.css` file (taken from https://unicons.iconscout.com/release/v3.0.0/css/line.css) to use them in my website. I installed the font from here (https://github.com/Iconscout/unicons/releases/download/v3.0.0/fonts.zip), unpacked the zip, modified the line.css file to adapt it to fonts hosted locally, but the problem now is that some icons work bad, and some a lot not at all.

Here my modifier version of line.css:

```css
@font-face {
  font-family: Unicons;
  src: url(../../fonts/unicons/unicons.woff2) format("woff2"), url(../../fonts/unicons/unicons.woff) format("woff"), url(../../fonts/unicons/unicons.ttf) format("truetype");
  font-weight: 400;
  font-style: normal;
  font-display: block
}

[class*=" uil-"]::before, [class^=uil-]::before {
  font-family: Unicons;
  font-style: normal;
  font-weight: 400;
  display: inline-block;
  text-decoration: inherit;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  letter-spacing: normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale
}


/* before, animations are here */
```
@tarunmangukiya maybe can you help me?

Thank you and have all a good day

**Comment by tarunmangukiya** [comment]
@Unknow-max Can you share a screenshot or something for reference?

**Comment by Unknow-max** [comment]
Hi, for sure!

First a quick **recap**: 
-  I installed the fonts from the 3.0.0 release on Github (https://github.com/Iconscout/unicons/releases/download/v3.0.0/fonts.zip).
- I installed locally from the CDN the ` CSS` file (https://unicons.iconscout.com/release/v3.0.0/css/line.css).

obviously I modified the file to adapt it to local fonts, now it looks like this:

```css

@font-face {
  font-family: unicons-line;
  src:  url(../../fonts/unicons/unicons.woff2) format('woff2'), url(../../fonts/unicons/unicons.woff) format('woff'), url(../../fonts/unicons/unicons.ttf) format('truetype'); // path to fonts
  font-weight: 400;
  font-style: normal;
}

[class^=uil-]:before, [class*=" uil-"]:before {
  font-family: unicons-line;
  font-style: normal;
  font-weight: 400;
  speak: none;
  display: inline-block;
  text-decoration: inherit;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale
}

/* animations, before codes, ecc */

```

Now as said when I try to use an icon, it do not work. Here the markup that I use:
```html
    <span class="uil-create-dashboard overview-tab__icon-inner icon-primary"></span>
```

The `before` code for the icon (create-dashboard) in my css file is:

```css
.uil-create-dashboard:before {
  content: '\ec5e'
}
```

The `: before` code is right.

But this is the result:

![immagine](https://user-images.githubusercontent.com/59534318/91039174-59deef80-e60c-11ea-9733-3daebf1267d2.png)

 Here are the styles applied to the pseudoelement:

![immagine](https://user-images.githubusercontent.com/59534318/91039261-8b57bb00-e60c-11ea-9763-dc6c635db831.png)

If I try to instead the fonts in your CDN  (https://unicons.iconscout.com/release/v3.0.0/fonts/line/unicons-0.woff.....), from my local CSS file all work fine.

The issue seems in the font.

Have a good day!
