### ISSUE TITLE
Icon padding

### ISSUE THREAD

**Issue by davestewart** [Iconscout/unicons#81]
Hi there,

Loving the icons! I'm just about to finish replacing Font Awesome with Unicions.

However, one thing I am noticing, is that the icons can look a bit weedy in comparison to FA, because each of the icons has built-in padding:

![image](https://user-images.githubusercontent.com/132681/83534424-ba1c3480-a4e8-11ea-9eff-b2bc01a078fe.png)

This is accentuated by the fact the lines can look a little slim, so sometimes a particular Unicon icon at 16px will look distinctly smaller than an equivalent Font Awesome icon at 16px.

I've been experimenting with workarounds like `font-size: 1.2em; margin: -.1em)` but do you have any advice to counteract this?

Thanks,
Dave

**Comment by tarunmangukiya** [comment]
Hi @davestewart,

Thanks for drawing attention. Can you share a codepen link for demo? So I can try it out and provide best solution.

**Comment by davestewart** [comment]
Sure. Just on something else right now, but will come back to it!

**Comment by davestewart** [comment]
Crikey. Even the pseudo-class is padded.

This is your site; note the font-size of 22px but the overall icon size of 30px.

![image](https://user-images.githubusercontent.com/132681/83540182-dcfe1700-a4ef-11ea-9a90-024c83d00192.png)

![image](https://user-images.githubusercontent.com/132681/83540220-eab39c80-a4ef-11ea-924c-34eb050f5478.png)

How is one supposed to build pixel-perfect designs, for example, context menus with all this extra space taking up room?

**Comment by tarunmangukiya** [comment]
Hmm! This seems fair point.

I just observed couple of libraries. I think you're right and we should allow users to handle spacing on their own.

Below are my current observations:
1. We are using [Fontello](https://github.com/fontello/fontello) to generate our font icons and used it as a base for Unicons font icons css too. This has caused to add the extra margin available in the `::before` psuedo-class.
2. Our icon design guideline is to leave space around the icon, so that they look consistent with text in size. i.e. a little 2px spacing in 24px icon.

I've tried a workaround, and we can add this in next release to fix this issue. Can you try to add this CSS code in your project and tell me your view:

```css
.uil {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    display: inline-block;
    font-style: normal;
    font-variant: normal;
    text-rendering: auto;
    line-height: 1;
    font-family: unicons;
    font-style: normal;
    font-weight: 400;
    speak: none;
}

[class^="uil-"]:before,
[class*=" uil-"]:before {
    margin-left: 0;
    margin-right: 0;
    line-height: inherit;
    width: auto;
}
```
