### ISSUE TITLE
Margin Issue for Line Icons CSS

### ISSUE THREAD

**Issue by tarunmangukiya** [Iconscout/unicons#82]
As per https://github.com/Iconscout/unicons/issues/81, we'll need to change our styling to make the UI pixel perfect. The proposed solution for it can be like below:

```css
.uil {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    display: inline-block;
    font-style: normal;
    font-variant: normal;
    text-rendering: auto;
    line-height: 1;
    font-family: unicons;
    font-style: normal;
    font-weight: 400;
    speak: none;
}
```

And remove extra `::before` css for psuedo-class.
